-- Qalqon — 0010_better_auth.sql
-- Better Auth core tables (TZ v2 §5.1, §6). Generated by running
-- `getMigrations()` from `better-auth/db/migration` against the actual
-- installed better-auth@1.7.5 with our config (see TZ v2 §18.2 — "compare
-- exact signatures against the installed version"), then hand-reviewed.
--
-- Column names are camelCase and double-quoted on purpose: this is exactly
-- what Better Auth's Postgres adapter queries, so it must not be
-- "normalized" to snake_case. Do not edit these tables by hand afterwards —
-- extend only via `additionalFields` in lib/auth/index.ts + a new
-- generated migration.
--
-- `user` replaces `app_users` (dropped in 0011_auth_extra.sql): `orgId`,
-- `appRole`, `telegramId`, `pinHash`, ... are Better Auth
-- `additionalFields`, all server-written (`input: false`).

create table "user" (
  "id"              uuid default pg_catalog.gen_random_uuid() not null primary key,
  "name"            text not null,
  "email"           text not null unique,
  "emailVerified"   boolean not null,
  "image"           text,
  "createdAt"       timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"       timestamptz default CURRENT_TIMESTAMP not null,
  "telegramId"      text,
  "telegramUsername" text,
  "fullName"        text,
  "appRole"         text,
  "orgId"           text,
  "pinHash"         text,
  "failedPinCount"  integer,
  "lockedUntil"     timestamptz,
  "isActive"        boolean
);

create table "session" (
  "id"          uuid default pg_catalog.gen_random_uuid() not null primary key,
  "expiresAt"   timestamptz not null,
  "token"       text not null unique,
  "createdAt"   timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"   timestamptz not null,
  "ipAddress"   text,
  "userAgent"   text,
  "userId"      uuid not null references "user" ("id") on delete cascade,
  "deviceId"    text
);

create table "account" (
  "id"                    uuid default pg_catalog.gen_random_uuid() not null primary key,
  "accountId"             text not null,
  "providerId"            text not null,
  "userId"                uuid not null references "user" ("id") on delete cascade,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope"                 text,
  "password"              text,
  "createdAt"             timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"             timestamptz not null
);

create table "verification" (
  "id"          uuid default pg_catalog.gen_random_uuid() not null primary key,
  "identifier"  text not null,
  "value"       text not null,
  "expiresAt"   timestamptz not null,
  "createdAt"   timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"   timestamptz default CURRENT_TIMESTAMP not null
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- Not generated by Better Auth itself, but required by our own login flow
-- (findUserByTelegramId / findUserByOrg) — additionalFields get no index
-- automatically.
create unique index "user_telegram_id_idx" on "user" ("telegramId") where "telegramId" is not null;
create index "user_org_id_idx" on "user" ("orgId") where "orgId" is not null;
